</$objtype/mkfile

TARG=send\
	filter

UOFILES=message.$O\
	dest.$O\
	log.$O\
	skipequiv.$O\

OFILES=\
	$UOFILES\
	../smtp/rfc822_parse.$O\

SMOBJ=main.$O\
	bind.$O\
	rewrite.$O\
	local.$O\
	translate.$O\
	authorize.$O\
	gateway.$O\
	cat_mail.$O\

LIB=../common/libcommon.av\

HFILES=send.h\
	../common/common.h\
	../common/sys.h\

LIB=../common/libcommon.a$O\

BIN=/$objtype/bin/upas
UPDATE=\
	mkfile\
	$HFILES\
	${UOFILES:%.$O=%.c}\
	${SMOBJ:%.$O=%.c}\
	${TARG:%=%.c}\

</sys/src/cmd/mkmany
CFLAGS=$CFLAGS -I../common

$O.send: $SMOBJ $OFILES
	$LD $LDFLAGS -o $target $prereq $LIB

message.$O:	../smtp/rfc822_parse.h

../smtp/rfc822_parse.h ../smtp/rfc822_parse.$O:
	@{
		cd ../smtp
		mk rfc822_parse.$O
	}
