< /$objtype/mkfile

TARG=pic
OFILES=	picy_parse.$O\
	picl.$O\
	main.$O\
	print.$O\
	misc.$O\
	symtab.$O\
	blockgen.$O\
	boxgen.$O\
	circgen.$O\
	arcgen.$O\
	linegen.$O\
	movegen.$O\
	textgen.$O\
	input.$O\
	for.$O\
	pltroff.$O\

HFILES=pic.h\
	picy_parse.h\

CLEANFILES=picl.c\

BIN=/$objtype/bin
</sys/src/cmd/mkone
CC=pcc
LD=pcc
CFLAGS=-FTV -c

picl.c: picl.lx
	$LEX -t $prereq > $target
