APE=/sys/src/ape
<$APE/config

DIRS=port $CPUS

default:V:	all

install all:V:
	for(i in port $objtype)@{
		echo $i
		cd $i
		mk $MKFLAGS $target
	}

clean:V:
	for(i in $DIRS)@{
		echo $i
		cd $i
		mk $MKFLAGS $target
	}

nuke:V: clean
	rm -f /$objtype/lib/ape/libsec.a

installall:V:
	for(objtype in $CPUS) mk $MKFLAGS install

everything:V:
	rm -f */*.[4679jx]
	for(objtype in $CPUS)@{
		echo $objtype
		mk $MKFLAGS install
	}
	rm -f */*.[4679jx]
