APE=/sys/src/ape
<$APE/config

TARG=make
OFILES=ident.$O\
	main.$O\
	doname.$O\
	dosys.$O\
	gram_parse.$O\
	misc.$O\
	files.$O\

HFILES=defs.h

BIN=$APEBIN
</sys/src/cmd/mkone

CFLAGS=-c -DSHELLCOM'="/bin/sh"'

nuke clean:V:
	rm -f *.[$OS] [$OS].out $TARG
