</$objtype/mkfile

TARG=fdisk prep

HFILES=edit.h
OFILES=\
	edit.$O\
	calc_parse.$O\

BIN=/$objtype/bin/disk

UPDATE=\
	mkfile\
	/sys/man/8/prep\
	edit.c\
	calc_parse.c\
	${TARG:%=%.c}\
	$HFILES\
	${TARG:%=/amd64/bin/disk/%}\

</sys/src/cmd/mkmany
