</$objtype/mkfile

TARG=execnet

OFILES=\
	client.$O\
	fs.$O\
	main.$O\
	note.$O\

HFILES=dat.h

BIN=/$objtype/bin
UPDATE=\
	mkfile\
	$HFILES\
	${OFILES:%.$O=%.c}\
	${TARG:%=/amd64/bin/%}\

</sys/src/cmd/mkone
