</$objtype/mkfile

TARG=9l
OFILES=\
	asm.$O\
	asmout.$O\
	list.$O\
	noop.$O\
	obj.$O\
	optab.$O\
	pass.$O\
	span.$O\
	enam.$O\
	cnam.$O\
	sched.$O\
	compat.$O\
	elf.$O\

HFILES=\
	l.h\
	../9c/9.out.h\
	../ld/elf.h\

BIN=/$objtype/bin
CFLAGS=$CFLAGS -. -I.
</sys/src/cmd/mkone

enam.$O:	../9c/enam.c
	$CC $CFLAGS ../9c/enam.c
elf.$O:	../ld/elf.c
	$CC $CFLAGS ../ld/elf.c
cnam.c:	l.h
	rc mkcname
