# 32-bit boot (pc/vt4/vt5) removed
ARCH=

all:V:
	@{ echo 'boot/mkfile: no 32-bit boot left' }

installall install:V:
	@{ echo 'boot/mkfile: no 32-bit boot left' }

clean:V:
	@{ echo 'boot/mkfile: no 32-bit boot left' }
