</$objtype/mkfile

LIB=/$objtype/lib/libflate.a
OFILES=\
	deflate.$O\
	deflatezlib.$O\
	deflateblock.$O\
	deflatezlibblock.$O\
	inflate.$O\
	inflatezlib.$O\
	inflateblock.$O\
	inflatezlibblock.$O\
	flateerr.$O\
	crc.$O\
	adler.$O\

HFILES=\
	/sys/include/flate.h\
	zlib.h\

UPDATE=\
	mkfile\
	$HFILES\
	${OFILES:%.$O=%.c}\
	${LIB:/$objtype/%=/amd64/%}\

</sys/src/cmd/mksyslib
