#!/usr/bin/env bash

set -e
cd $(dirname $0)/..

lst=( \
	./acme/bin/amd64 \
	./acme/bin/arm64 \
	./acme/bin/mips64 \
	./acme/bin/power64 \
	./acme/bin/riscv64 \
	./acme/bin/spim64 \
	./amd64/bin \
	./amd64/bin/ape \
	./amd64/bin/auth \
	./amd64/bin/aux \
	./amd64/bin/bitsy \
	./amd64/bin/dial \
	./amd64/bin/disk \
	./amd64/bin/fossil \
	./amd64/bin/fs \
	./amd64/bin/games \
	./amd64/bin/ip/httpd \
	./amd64/bin/ndb \
	./amd64/bin/replica \
	./amd64/bin/upas \
	./amd64/bin/usb \
	./amd64/bin/venti \
	./amd64/lib \
	./amd64/lib/ape \
	./arm64/bin/ape \
	./arm64/bin/auth \
	./arm64/bin/aux \
	./arm64/bin/bitsy \
	./arm64/bin/dial \
	./arm64/bin/disk \
	./arm64/bin/fossil \
	./arm64/bin/fs \
	./arm64/bin/games \
	./arm64/bin/git \
	./arm64/bin/ip/httpd \
	./arm64/bin/ndb \
	./arm64/bin/replica \
	./arm64/bin/upas \
	./arm64/bin/usb \
	./arm64/bin/venti \
	./arm64/lib/ape \
	./dist/replica/client \
	./env \
	./fd \
	./lib/audio \
	./lib/face/48x48x1/o \
	./lib/face/48x48x1/v \
	./lib/face/48x48x1/x \
	./lib/face/48x48x1/y \
	./lib/face/48x48x1/z \
	./lib/face/48x48x2/f \
	./lib/face/48x48x2/i \
	./lib/face/48x48x2/l \
	./lib/face/48x48x2/m \
	./lib/face/48x48x2/n \
	./lib/face/48x48x2/o \
	./lib/face/48x48x2/q \
	./lib/face/48x48x2/u \
	./lib/face/48x48x2/v \
	./lib/face/48x48x2/w \
	./lib/face/48x48x2/x \
	./lib/face/48x48x2/y \
	./lib/face/48x48x2/z \
	./lib/face/48x48x4/i \
	./lib/face/48x48x4/o \
	./lib/face/48x48x4/q \
	./lib/face/48x48x4/y \
	./lib/face/48x48x4/z \
	./lib/face/48x48x4/Z \
	./lib/face/48x48x8/i \
	./lib/face/48x48x8/o \
	./lib/face/48x48x8/w \
	./lib/face/48x48x8/x \
	./lib/face/48x48x8/Z \
	./lib/ndb/dhcp \
	./lib/news \
	./lib/tftpd \
	./lp/log \
	./lp/prob \
	./lp/queue \
	./lp/tmp \
	./mail/faxoutqueue \
	./mail/fs \
	./mail/grey/tmp \
	./mail/queue \
	./mail/tmp \
	./mnt/acme \
	./mnt/apeselect \
	./mnt/apm \
	./mnt/arch \
	./mnt/cd \
	./mnt/cons/cons \
	./mnt/cons/consctl \
	./mnt/consoles \
	./mnt/doc \
	./mnt/exportfs/0 \
	./mnt/exportfs/1 \
	./mnt/exportfs/10 \
	./mnt/exportfs/11 \
	./mnt/exportfs/12 \
	./mnt/exportfs/13 \
	./mnt/exportfs/14 \
	./mnt/exportfs/15 \
	./mnt/exportfs/16 \
	./mnt/exportfs/2 \
	./mnt/exportfs/3 \
	./mnt/exportfs/4 \
	./mnt/exportfs/5 \
	./mnt/exportfs/6 \
	./mnt/exportfs/7 \
	./mnt/exportfs/8 \
	./mnt/exportfs/9 \
	./mnt/keys \
	./mnt/lp \
	./mnt/netkeys \
	./mnt/news \
	./mnt/plumb \
	./mnt/rdb \
	./mnt/temp \
	./mnt/term \
	./mnt/ums \
	./mnt/vmware \
	./mnt/web \
	./mnt/webcookies \
	./mnt/wiki \
	./mnt/wrap \
	./mnt/wsys \
	./n/9 \
	./n/9fat \
	./n/a \
	./n/a: \
	./n/b \
	./n/boot \
	./n/c \
	./n/c: \
	./n/d: \
	./n/dist \
	./n/fossil \
	./n/ftp \
	./n/kfs \
	./n/kremvax \
	./n/paq \
	./n/sid \
	./n/snap \
	./n/sources \
	./n/sourcesdump \
	./n/sourcessnap \
	./n/tapefs \
	./n/temp \
	./n/vac \
	./power64/bin/ape \
	./power64/bin/auth \
	./power64/bin/aux \
	./power64/bin/bitsy \
	./power64/bin/dial \
	./power64/bin/disk \
	./power64/bin/fossil \
	./power64/bin/fs \
	./power64/bin/games \
	./power64/bin/ip/httpd \
	./power64/bin/ndb \
	./power64/bin/replica \
	./power64/bin/upas \
	./power64/bin/usb \
	./power64/bin/venti \
	./power64/lib/ape \
	./rc/bin/dial \
	./rc/bin/postscript \
	./riscv64/bin/ape \
	./riscv64/bin/auth \
	./riscv64/bin/aux \
	./riscv64/bin/bitsy \
	./riscv64/bin/dial \
	./riscv64/bin/disk \
	./riscv64/bin/fossil \
	./riscv64/bin/fs \
	./riscv64/bin/games \
	./riscv64/bin/git \
	./riscv64/bin/ip/httpd \
	./riscv64/bin/ndb \
	./riscv64/bin/replica \
	./riscv64/bin/upas \
	./riscv64/bin/usb \
	./riscv64/bin/venti \
	./riscv64/lib/ape \
	./mips64/bin/ape \
	./mips64/bin/auth \
	./mips64/bin/aux \
	./mips64/bin/dial \
	./mips64/bin/disk \
	./mips64/bin/venti \
	./mips64/lib/ape \
	./spim64/bin/ape \
	./spim64/lib/ape \
	./sys/games/sudoku \
	./sys/lib/backup/set1 \
	./sys/lib/dist/bin/amd64 \
	./sys/lib/dist/pc/empty \
	./sys/lib/dist/pc/glenda/tmp \
	./sys/lib/dist/pc/multi \
	./sys/lib/lp/log \
	./sys/lib/lp/perm \
	./sys/lib/lp/tmp \
	./sys/lib/postscript/afm \
	./sys/lib/ssh \
	./sys/lib/troff/contour \
	./sys/log/timesync.d \
	./sys/src/cmd/ip/rtcp \
	./sys/src/cmd/unix/drawterm/bin \
	./tmp \
	./usr/glenda/bin/amd64 \
	./usr/glenda/bin/arm64 \
	./usr/glenda/tmp \
)

for i in "${lst[@]}"; do
	mkdir -p $i
done

lst=( \
	./mail/box/glenda/mbox
)

for i in "${lst[@]}"; do
	touch $i
done

lst=( \
	./sys/src/9k/root/nvram
)

for i in "${lst[@]}"; do
	mkdir -p $(dirname $i)
	[ -f $i ] || dd if=/dev/zero of=$i bs=512 count=1 status=none
done

lst=( \
)

for i in "${lst[@]}"; do
	[ -d $(dirname $i) ] && touch $i
done
