NPROC=1
</$objtype/mkfile

install:V:
	SYS=`{sed '/^#define._X[123]/d; s/#define.([A-Z0-9_]*).*/\1/' sys.h}
	for(I in $SYS) {
		i=`{echo $I|tr A-Z a-z}
		n=`{sed -n '/[ 	]'$I'[ 	]/s/.*	//p' sys.h}
		if(~ $i exits) i=_exits
		{switch($objtype){
		case mips64
			if(~ $i seek || ~ $i nsec)
				echo TEXT _$i'(SB)', 1, '$0'
			if not
				echo TEXT $i'(SB)', 1, '$0'
			echo MOVV R1, '0(FP)'
			echo MOVW '$'$n, R1
			echo ADDV '$8',R29
			echo SYSCALL
			echo ADDV '$-8',R29
			echo RET
		case spim64
			if(~ $i seek || ~ $i nsec)
				echo TEXT _$i'(SB)', 1, '$0'
			if not
				echo TEXT $i'(SB)', 1, '$0'
			echo MOVV R1, '0(FP)'
			echo MOVW '$'$n, R1
			echo ADDV '$8',R29
			echo SYSCALL
			echo ADDV '$-8',R29
			echo RET
		case amd64
			if(~ $i seek)
				echo TEXT _seek'(SB)', 1, '$0'
			if not
				echo TEXT $i'(SB)', 1, '$0'
			#
			# For architectures which pass the first argument
			# in a register, if the system call takes no arguments
			# there will be no 'a0+0(FP)' reserved on the stack.
			#
			if(! ~ $i nsec)
				echo MOVQ RARG, 'a0+0(FP)'
			echo MOVQ '$'$n, RARG
			echo SYSCALL
			echo RET
		case arm64
			if(~ $i seek)
				echo TEXT _seek'(SB)', 1, '$0'
			if not
				echo TEXT $i'(SB)', 1, '$0'
			echo MOV R0, '0(FP)'
			echo MOV '$'$n, R0
			echo SVC
			echo RETURN
		case power64
			if(~ $i seek)
				echo TEXT _seek'(SB)', 1, '$0'
			if not
				echo TEXT $i'(SB)', 1, '$0'
			echo MOVD R3, '0(FP)'
			echo MOVW '$'$n, R3
			echo SYSCALL
			echo RETURN
		case riscv64
			if(~ $i seek)
				echo TEXT _seek'(SB)', 1, '$0'
			if not
				echo TEXT $i'(SB)', 1, '$0'
			#
			# For architectures which pass the first argument
			# in a register, if the system call takes no arguments
			# there will be no 'a0+0(FP)' reserved on the stack.
			#
			# jc doesn't widen longs to vlongs when pushing them.
			# so we have to be careful here to only push longs
			# for first arguments, where appropriate.
			#
			switch ($i) {
			case nsec
				;
			case bind chdir exec _exits segbrk open create \
			    brk_ remove notify pipe seek segdetach segfree \
			    segflush rendezvous unmount semacquire \
			    semrelease errstr stat wstat await tsemacquire
				echo MOV R8, '0(FP)'
			case *
				echo MOVW R8, '0(FP)'
			}
			echo MOV '$'$n, R8
			echo ECALL
			echo RET
		}} > $i.s
		$AS $i.s
	}
	ar vu /$objtype/lib/libc.a *.$O
	rm -f *.$O *.s

nuke clean:V:
	rm -f *.[$OS]

installall:V:
	for(objtype in $CPUS) mk install

update:V:
	update $UPDATEFLAGS mkfile sys.h
