</$objtype/mkfile

TARG=page

# NOTE (commercial build): gs/ps/pdf stubbed (AFPL gs removed);
# gs.$O, ps.$O, pdf.$O kept so page still builds for image/FAX/troff.
HFILES=page.h
OFILES=\
	cache.$O\
	filter.$O\
	gfx.$O\
	gs.$O\
	page.$O\
	pdf.$O\
	ps.$O\
	rotate.$O\
	util.$O\
	view.$O\

LIB=/$objtype/lib/libdraw.a

UPDATE=\
	mkfile\
	${OFILES:%.$O=%.c}\
	pdfprolog.ps\
	$HFILES\
	/sys/man/1/page\
	/amd64/bin/page\

</sys/src/cmd/mkone

BIN=/$objtype/bin

pdfprolog.c: pdfprolog.ps
	cat pdfprolog.ps | sed 's/.*/"&\\n"/g' >pdfprolog.c

pdf.$O: pdfprolog.c

