</$objtype/mkfile

TARG = smtpd\
	smtp\

OFILES=

LIB=../common/libcommon.a$O\

HFILES=../common/common.h\
	../common/sys.h\
	smtpd.h\
	smtp.h\
	rfc822_parse.h\

BIN=/$objtype/bin/upas
UPDATE=\
	greylist.c\
	mkfile\
	mxdial.c\
	rmtdns.c\
	smtpd_parse.c\
	rfc822_parse.c\
	spam.c\
	$HFILES\
	${OFILES:%.$O=%.c}\
	${TARG:%=%.c}\

</sys/src/cmd/mkmany
CFLAGS=$CFLAGS -I../common -D'SPOOL="/mail"'

$O.smtpd:	smtpd_parse.$O rmtdns.$O spam.$O rfc822_parse.$O greylist.$O
$O.smtp:	rfc822_parse.$O mxdial.$O

smtpd.$O: 	smtpd.h

smtp.$O to.$O: 	smtp.h

smtpd_parse.$O rfc822_parse.$O: rfc822_parse.h smtp.h smtpd.h

clean:V:
	rm -f *.[$OS] [$OS].$TARG $TARG

../common/libcommon.a$O:
	@{ 	
		cd ../common
		mk
	}
