/* Hand-written replacement for y.tab.h generated by
 * `yacc -d -o rfc822.tab.c rfc822.y'.
 * Token numbers match yacc declaration order (single chars keep ASCII).
 */
enum {
	WORD = 257,
	DATE = 258,
	RESENT_DATE = 259,
	RETURN_PATH = 260,
	FROM = 261,
	SENDER = 262,
	REPLY_TO = 263,
	RESENT_FROM = 264,
	RESENT_SENDER = 265,
	RESENT_REPLY_TO = 266,
	SUBJECT = 267,
	TO = 268,
	CC = 269,
	BCC = 270,
	RESENT_TO = 271,
	RESENT_CC = 272,
	RESENT_BCC = 273,
	REMOTE = 274,
	PRECEDENCE = 275,
	MIMEVERSION = 276,
	CONTENTTYPE = 277,
	MESSAGEID = 278,
	RECEIVED = 279,
	MAILER = 280,
	BADTOKEN = 281,
};
