</$objtype/mkfile

TARG=awk
OFILES=re.$O\
	lex.$O\
	main.$O\
	parse.$O\
	proctab.$O\
	tran.$O\
	lib.$O\
	run.$O\
	awkgram_parse.$O\

HFILES=awk.h\
	awkgram_parse.h\
	proto.h\

BIN=/$objtype/bin

UPDATE=\
	mkfile\
	awk.h proto.h\
	re.c lex.c main.c parse.c proctab.c tran.c lib.c run.c\
	maketab.c\
	${TARG:%=/amd64/bin/%}\

</$objtype/mkfile
CFLAGS=-FTV -c -D_REGEXP_EXTENSION -D_RESEARCH_SOURCE -D_BSD_EXTENSION -DUTF
CC=pcc
LD=pcc
cpuobjtype=`{sed -n 's/^O=//p' /$cputype/mkfile}

clean:V:
	rm -f *.[$OS] [$OS].out [$OS].maketab y.debug y.output $TARG

nuke:V:
	rm -f *.[$OS] [$OS].out [$OS].maketab y.debug y.output awkgram.c $TARG

proctab.c:	$cpuobjtype.maketab
	./$cpuobjtype.maketab >proctab.c

$cpuobjtype.maketab:	awkgram_parse.h maketab.c
	objtype=$cputype
	mk maketab.$cputype

maketab.$cputype:V:	awkgram_parse.h maketab.$O
	$LD -o $O.maketab maketab.$O
