</$objtype/mkfile

TARG=lex
OFILES=lmain.$O\
	parser_parse.$O\
	sub1.$O\
	sub2.$O\
	header.$O\

HFILES=ldefs.h\


BIN=/$objtype/bin
UPDATE=\
	mkfile\
	$HFILES\
	lmain.c\
	sub1.c\
	sub2.c\
	header.c\
	${TARG:%=/amd64/bin/%}\

</sys/src/cmd/mkone

installall:V:
	for(objtype in $CPUS)
		mk install
	cp ncform /sys/lib/lex
