</$objtype/mkfile
CFLAGS = $CFLAGS -DIOUNIT=8192

TARG=7a
OFILES=\
	a_parse.$O\
	lex.$O\

HFILES=\
	../7c/7.out.h\
	a_parse.h\
	a.h\

BIN=/$objtype/bin
< /sys/src/cmd/mkone

lex.$O:	../cc/macbody ../cc/lexbody ../cc/compat

