# 32-bit kernels removed; 64-bit kernels live in
# sys/src/9k/k10, sys/src/9/bcm64, sys/src/9/loongson64
ARCH=

all:V:
	@{ echo '9/mkfile: no 32-bit kernels left' }

installall install:V:
	@{ echo '9/mkfile: no 32-bit kernels left' }

clean:V:
	@{ echo '9/mkfile: no 32-bit kernels left' }
