</$objtype/mkfile

LIB=/$objtype/lib/libmach.a
FILES=\
	executable\
	map\
	obj\
	swap\
	sym\
	access\
	machdata\
	setmach\
	sparc64\
	68020\
	alpha\
	4\
	6\
	7\
	9\
	j\
	sparc64db\
	68020db\
	alphadb\
	8db\
	vdb\
	qdb\
	idb\
	6obj\
	7obj\
	9obj\
	4obj\
	68020obj\
	alphaobj\

HFILES=/sys/include/mach.h elf.h obj.h

CFILES=${FILES:%=%.c}

OFILES=${FILES:%=%.$O}

UPDATE=mkfile\
	/amd64/lib/libmach.a\
	$HFILES\
	$CFILES\

</sys/src/cmd/mksyslib

CFLAGS=$CFLAGS -I/sys/src/cmd

68020obj.$O: 68020/2.out.h
4obj.$O: 4c/4.out.h
6obj.$O: /sys/src/cmd/6c/6.out.h
7obj.$O: /sys/src/cmd/7c/7.out.h
9obj.$O: 9c/9.out.h
alphaobj.$O: alpha/7.out.h
sparc64obj.$O: sparc64/u.out.h
