</$objtype/mkfile

TARG=troff2html
HFILES=chars.h
OFILES=troff2html.$O\

BIN=/$objtype/bin
</sys/src/cmd/mkone
CFLAGS=$CFLAGS -DLUCENT

outsideinstall:V: /amd64/bin/troff2html
	9fs outside
	cp /amd64/bin/troff2html /n/outside/amd64/bin/troff2html

