# 32-bit nboot (bitsy/pc/zynq) removed; only efi (bootx64) left
ARCH=\
	efi\

all:V:
	for(i in $ARCH)@{
		cd $i
		mk
	}

installall install:V:
	for(i in $ARCH) @{
		cd $i
		mk install
	}

clean:V:
	for(i in $ARCH) @{
		cd $i
		mk clean
	}
