</$objtype/mkfile

TARG=rc
COMMONOFILES=\
	code.$O\
	exec.$O\
	glob.$O\
	here.$O\
	io.$O\
	lex.$O\
	pcmd.$O\
	pfnc.$O\
	simple.$O\
	subr.$O\
	trap.$O\
	tree.$O\
	var.$O\
	havefork.$O\

PLAN9OFILES=plan9.$O\

UNIXOFILES=unix.$O\

OFILES=$COMMONOFILES $PLAN9OFILES syn_parse.$O

HFILES=rc.h\
	syn_parse.h\
	io.h\
	exec.h\
	fns.h

BIN=/$objtype/bin

UPDATE=\
	mkfile\
	$HFILES\
	${COMMONOFILES:%.$O=%.c}\
	${UNIXOFILES:%.$O=%.c}\
	${PLAN9OFILES:%.$O=%.c}\
	${TARG:%=/amd64/bin/%}\

</sys/src/cmd/mkone

clean:V:
	rm -f [$OS].out *.[$OS] y.debug $TARG

regress: $O.out
	cd test
	mk

unregress:V:
	for(test in test/*.test) rc $test >$test.out

listing:
	pr mkfile $HFILES $FILES $FILES9 $FILESUNIX|lp -du
