</$objtype/mkfile

TARG=grap
OFILES=\
	grap_parse.$O\
	grapl.$O\
	main.$O\
	input.$O\
	print.$O\
	frame.$O\
	for.$O\
	coord.$O\
	ticks.$O\
	plot.$O\
	label.$O\
	misc.$O\

HFILES=grap.h\
	grap_parse.h\

LFILES=grapl.lx\

CLEANFILES=grapl.c\

BIN=/$objtype/bin
</sys/src/cmd/mkone
CC=pcc
LD=pcc
CFLAGS=-FTV -c

grapl.c: $LFILES
	$LEX -t $prereq > $target
