</$objtype/mkfile

TARG=6a
OFILES=\
	a_parse.$O\
	lex.$O\

HFILES=\
	../6c/6.out.h\
	a_parse.h\
	a.h\

BIN=/$objtype/bin
UPDATE=\
	mkfile\
	lex.c\
	a.h\
	${TARG:%=/amd64/bin/%}\

< /sys/src/cmd/mkone

lex.$O:	../cc/macbody ../cc/lexbody ../cc/compat
