</$objtype/mkfile

LIB=/$objtype/lib/libcomplete.a
OFILES=\
	complete.$O\

HFILES=/sys/include/complete.h

UPDATE=\
	mkfile\
	$HFILES\
	${OFILES:%.$O=%.c}\
	${LIB:/$objtype/%=/amd64/%}\

</sys/src/cmd/mksyslib
