</$objtype/mkfile

TARG=ja

OFILES=\
	a_parse.$O\
	lex.$O\

HFILES=\
	../jc/j.out.h\
	a_parse.h\
	a.h\

BIN=/$objtype/bin

< /sys/src/cmd/mkone

$O.ja: $OFILES
	$LD $LDFLAGS -o $target $prereq

lex.$O:	../cc/macbody ../cc/lexbody ../cc/compat

install:V:	$BIN/$TARG

$BIN/$TARG:	$O.out
	cp $prereq $target
