</$objtype/mkfile

LIB=/$objtype/lib/libthread.a

OFILES=\
	$objtype.$O\
	channel.$O\
	chanprint.$O\
	create.$O\
	debug.$O\
	dial.$O\
	exec.$O\
	exit.$O\
	id.$O\
	iocall.$O\
	ioclose.$O\
	iodial.$O\
	ioopen.$O\
	ioproc.$O\
	ioread.$O\
	ioreadn.$O\
	iosleep.$O\
	iowrite.$O\
	kill.$O\
	lib.$O\
	main.$O\
	note.$O\
	ref.$O\
	rendez.$O\
	sched.$O\

CFILES=\
	amd64.c\
	arm64.c\
	mips64.c\
	power64.c\
	riscv64.c\
	spim64.c\
	channel.c\
	chanprint.c\
	create.c\
	debug.c\
	dial.c\
	example.c\
	exec.c\
	exit.c\
	id.c\
	iocall.c\
	ioclose.c\
	iodial.c\
	ioopen.c\
	ioproc.c\
	ioread.c\
	ioreadn.c\
	iowrite.c\
	kill.c\
	lib.c\
	main.c\
	note.c\
	rendez.c\
	sched.c\
	test.c\
	tprimes.c\

HFILES=\
	/sys/include/thread.h\
	threadimpl.h\

UPDATE=mkfile\
	/amd64/lib/libthread.a\
	$HFILES\
	$CFILES\
	$SFILES\

all:V:	$LIB sched.acid channel.acid

</sys/src/cmd/mksyslib

$O.tprimes: tprimes.$O $LIB
	$LD -o $target $prereq
