</$objtype/mkfile

TARG=jl

OFILES=\
	asm.$O\
	compress.$O\
	list.$O\
	noop.$O\
	obj.$O\
	optab.$O\
	pass.$O\
	span.$O\
	enam.$O\
	compat.$O\
	elf.$O\

HFILES=\
	l.h\
	../jc/j.out.h\
	../ld/elf.h\

BIN=/$objtype/bin
CFLAGS=$CFLAGS -. -I.
</sys/src/cmd/mkone

enam.$O:	../jc/enam.c
	$CC $CFLAGS ../jc/enam.c
elf.$O:	../ld/elf.c
	$CC $CFLAGS ../ld/elf.c

x:V:	$O.out
	$O.out -la -o/dev/null x.i

test:V:	$O.out
	rm -f xxx
	mv $O.out xxx
	./xxx $OFILES
	cmp $O.out xxx

install:V:	$BIN/$TARG

$BIN/$TARG:	$O.out
	cp $prereq $target
