</$objtype/mkfile

TARG=acid
UOFILES=	main.$O\
	lex.$O\
	util.$O\
	exec.$O\
	expr.$O\
	list.$O\
	builtin.$O\
	proc.$O\
	dot.$O\
	print.$O\

OFILES=$UOFILES dbg_parse.$O

HFILES=acid.h\
	dbg_parse.h\

BIN=/$objtype/bin

UPDATE=\
	mkfile\
	$HFILES\
	${UOFILES:%.$O=%.c}\
	dbg_parse.c\

</sys/src/cmd/mkone

lex.$O:		dbg_parse.h
util.$O:	dbg_parse.h
builtin.$O:	dbg_parse.h
main.$O:	dbg_parse.h
proc.$O:	dbg_parse.h
