</$objtype/mkfile

DIRS=port $CPUS

default:V:	all

install all:V:
	for(i in port $objtype)@{
		echo $i
		cd $i
		mk $MKFLAGS $target
	}

nuke:V: clean
	rm -f /$objtype/lib/libmp.a

clean:V:
	for(i in $DIRS)@{
		echo $i
		cd $i
		mk $MKFLAGS $target
	}
update:V:
	for(i in $DIRS)@{
		echo $i
		cd $i
		mk $MKFLAGS $target
	}
	update /amd64/lib/libmp.a

installall:V:
	for(objtype in $CPUS) mk $MKFLAGS install

everything:V:
	rm -f */*.[4679jx]
	for(objtype in $CPUS)@{
		echo $objtype
		mk $MKFLAGS install
	}
	rm -f */*.[4679jx]

test.$O: test.c /$objtype/include/u.h /sys/include/mp.h port/dat.h
	$CC -Iport test.c

$O.test: test.$O /$objtype/lib/libmp.a
	$LD -o $O.test test.$O

bigtest.$O: bigtest.c /$objtype/include/u.h /sys/include/mp.h port/dat.h
	$CC -Iport bigtest.c

$O.bigtest: bigtest.$O /$objtype/lib/libmp.a
	$LD -o $O.bigtest bigtest.$O

allout:
	objtype=amd64; mk; mk 6.test 6.bigtest
	objtype=arm64; mk; mk 7.test 7.bigtest

cleanout:
	rm -f [67].* *.[67]
